'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useCart } from '@/components/cart/CartContext';
import { formatCurrency } from '@/lib/pricing';
export default function CartPage() {
  const { items, removeItem, subtotal, clearCart } = useCart();
  return <main className="section"><div className="container" style={{display:'grid',gridTemplateColumns:'1.5fr .9fr',gap:24}}><section><h1 className="display" style={{fontSize:'clamp(42px,7vw,76px)',margin:'0 0 22px'}}>Your cart</h1>{items.length === 0 ? <div className="card empty-state"><p className="eyebrow">Your cart is empty.</p><Link href="/shop" className="button button-primary" style={{marginTop:14}}>Browse products</Link></div> : <div className="table-list">{items.map((item) => <div key={item.id} className="card" style={{padding:18,display:'grid',gridTemplateColumns:'140px 1fr auto',gap:18,alignItems:'center'}}><Image src={item.image} alt={item.name} width={280} height={200} style={{borderRadius:16,objectFit:'cover'}} /><div><strong style={{fontSize:22}}>{item.name}</strong><div className="muted">{item.quantity} tier • {item.size} • {item.finish}</div><div className="muted">Sets: {item.cartQuantity}</div></div><div style={{textAlign:'right'}}><strong>{formatCurrency(item.unitPrice * item.cartQuantity)}</strong><div style={{marginTop:10}}><button className="button button-outline" onClick={() => removeItem(item.id)}>Remove</button></div></div></div>)}</div>}</section><aside><div className="card summary-box"><h2 className="display" style={{fontSize:38,margin:'0 0 8px'}}>Summary</h2><div className="meta-row"><span>Subtotal</span><strong>{formatCurrency(subtotal)}</strong></div><div className="muted" style={{marginTop:8}}>Taxes and delivery are calculated at checkout.</div><div style={{display:'grid',gap:10,marginTop:18}}><Link href="/checkout" className="button button-primary">Continue to checkout</Link><button className="button button-outline" onClick={clearCart}>Clear cart</button></div></div></aside></div></main>;
}
